import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = join(root, 'client.js')
const sourceFiles = [
  'client/modules/workspace/index.js',
  'client/modules/service-manager/index.js',
  'client/modules/test/index.js',
  'client/modules/usage-stats/index.js',
  'client/modules/right-sidebar/vendor/core.js',
  'client/modules/right-sidebar/index.js',
  'client/main.js',
]

const output = sourceFiles
  .map(relativePath => {
    const source = readFileSync(join(root, relativePath), 'utf8').trim()
    return [
      `// @generated by scripts/build-client.js from ${relativePath}`,
      source.endsWith(';') ? source : source + ';',
    ].join('\n')
  })
  .join('\n\n') + '\n'

if (process.argv.includes('--check')) {
  const current = readFileSync(outputPath, 'utf8')
  if (current !== output) {
    console.error('client.js is out of date; run npm run build:client')
    process.exitCode = 1
  }
} else {
  writeFileSync(outputPath, output)
}
